### ISSUE TITLE
Data & Analytics Roadmap

### ISSUE THREAD

**Issue by Rello** [Rello/data#1]
### Datasources and connectors
- [ ] Nextcloud internal tables
- [ ] REST API
- [ ] hooks for 3rd party connectors
- [ ] import csv from files app
- [ ] public/external data entry form

### Visualisation
- [ ] dataset groups
- [ ] more chart options
- [ ] report export
- [ ] new data indicator in dataset list
- [ ] Dashboard widget

### Integration
- [ ] User sharing
- [ ] NC18 Workflow destination
- [ ] cron for snapshots?
- [ ] alerts/thresholds => Notifications
- [ ] Projects/Deck integration

**Comment by markuskramerIgitt** [comment]
Hi @Rello,  thank you for this app! I would like to use and contribute, but I have very little experience with nextcloud apps (yet). 

I need (and could help to create) user documentation for nextcloud beginners.

I want to use the "website grabber".

Chapter **Usage** in the [Wiki](https://github.com/Rello/analytics/wiki/Datasource:-website-grabber) says 

1. Report -> advanced config

Where do I find "advanced config"?

![image](https://user-images.githubusercontent.com/8489107/73127141-44dda780-3fbc-11ea-9e1f-3aac4abd2e3d.png)



Maybe I need to satisfy the condition "the datasource is only available in advanced config **with scheduling** due to the required parameters"?

How shall I enable scheduling?
